name: my_first_ci

# tell workflow when it will run
on: 
  pull_request:
  push:
    branches:
      - main
      - develop
  workflow_dispatch: # adds button to run workflow

# now the actual tasks
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: install python package
        run: python -m pip install .[test]
      - name: run tests
        run: python -m pytest

  # to save a lot of copy paste
  matrix-test:
    strategy: 
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.9', '3.11']
        include:
        - os: macos-latest
          python-version: '3.10'

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
      - name: install python package
        run: python -m pip install .[test]
      - name: run tests
        run: python -m pytest
      - name: example step that runs on linux
        if: runner.os == 'Linux'
        run: echo 'this is linux'
      - name: this step generates output
        id: step-with-output
        run: echo "some-variable=something" >> $GITHUB_OUTPUT
      - run: echo "${{steps.step-with-output.output.some-variable}}"