name: my_first_ci

# tell workflow when it will run
on: 
  pull_request:
  push:
    branches:
      - main
      - develop
  workflow_dispatch: # adds button to run workflow

# now the actual tasks
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: install python package
        run: python -m pip install .[test]
      - name: run tests
        run: python -m pytest